"""Create sleep_log table

Revision ID: 018f706bd149
Revises: 19dac3db677a
Create Date: 2025-02-11 12:19:03.180101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018f706bd149'
down_revision = '19dac3db677a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bedtime', sa.Time(), nullable=False),
    sa.Column('risetime', sa.Time(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=False),
    sa.Column('relative_quality', sa.Integer(), nullable=False),
    sa.Column('awakenings', sa.Integer(), nullable=False),
    sa.Column('OSA_interventions', sa.Boolean(), nullable=False),
    sa.Column('caffeine', sa.Boolean(), nullable=False),
    sa.Column('sleep_aid', sa.Boolean(), nullable=False),
    sa.Column('alcohol', sa.Boolean(), nullable=False),
    sa.Column('cannabis', sa.Boolean(), nullable=False),
    sa.Column('typical_day', sa.Boolean(), nullable=False),
    sa.Column('sleep_period_duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep_log')
    # ### end Alembic commands ###
